// Code generated by frourio-go. DO NOT EDIT.

package users

import "context"

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
	Query GetQuery
}

type GetQuery struct {
	Limit *int `json:"limit"`
}

type GetResponse interface {
	isGetResponse()
	StatusCode() int
}

type GetStatus200 struct {
	Body []string `json:"body"`
}

func (GetStatus200) isGetResponse()  {}
func (GetStatus200) StatusCode() int { return 200 }

type PostRequest struct {
	Body PostBody
}

type PostBody struct {
	Name string `json:"name" validate:"required"`
	Age  *int   `json:"age"`
}

type PostResponse interface {
	isPostResponse()
	StatusCode() int
}

type PostStatus201 struct {
	Body string `json:"body" validate:"required"`
}

func (PostStatus201) isPostResponse() {}
func (PostStatus201) StatusCode() int { return 201 }

type PostStatus400 struct {
	Body string `json:"body" validate:"required"`
}

func (PostStatus400) isPostResponse() {}
func (PostStatus400) StatusCode() int { return 400 }

type RouteHandlers struct {
	Get  func(context.Context, GetRequest) (GetResponse, error)
	Post func(context.Context, PostRequest) (PostResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
