// Code generated by frourio-go. DO NOT EDIT.

package secure

import (
	"context"
	"net/http"
)

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
}

type GetResponse interface {
	isGetResponse()
	StatusCode() int
}

type GetStatus200 struct {
	Body string `json:"body" validate:"required"`
}

func (GetStatus200) isGetResponse()  {}
func (GetStatus200) StatusCode() int { return 200 }

type MiddlewareAllContext struct {
	UserID  string `json:"userId" validate:"required"`
	TraceID string `json:"traceId" validate:"required"`
}

type MiddlewareContext struct {
	MiddlewareAllContext
}

type MiddlewareNext func(context.Context, MiddlewareAllContext) (any, error)
type MiddlewareAll func(context.Context, *http.Request, MiddlewareNext) (any, error)

type GetContext struct {
	MiddlewareContext
}

type RouteMiddleware struct {
	All MiddlewareAll
}

type RouteHandlers struct {
	Middleware RouteMiddleware
	Get        func(context.Context, GetRequest, GetContext) (GetResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
