// Code generated by frourio-go. DO NOT EDIT.

package public

import "context"

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
}

type GetResponse interface {
	isGetResponse()
	StatusCode() int
}

type GetStatus200 struct {
	Body string `json:"body" validate:"required"`
}

func (GetStatus200) isGetResponse()  {}
func (GetStatus200) StatusCode() int { return 200 }

type RouteHandlers struct {
	Get func(context.Context, GetRequest) (GetResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
