// Code generated by frourio-go. DO NOT EDIT.

package api

import "context"

type RouteDefinition struct {
	handlers RouteHandlers
	spec     routeMetadata
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
	Query GetQuery
}

type GetQuery struct {
	Search *string `json:"search"`
	Limit  *int    `json:"limit"`
}

type GetResponse interface {
	isGetResponse()
	StatusCode() int
}

type GetStatus200 struct {
	Body string `json:"body" validate:"required"`
}

func (GetStatus200) isGetResponse()  {}
func (GetStatus200) StatusCode() int { return 200 }

type RouteHandlers struct {
	Get func(context.Context, GetRequest) (GetResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{handlers: handlers, spec: routeSpec}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
