// Code generated by frourio-go. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"reflect"
	"strconv"
	"strings"

	auth "github.com/frourios/frourio-go/tests/apps/basic/api/auth"
	blogSlug "github.com/frourios/frourio-go/tests/apps/basic/api/blog/slug"
	filesPath "github.com/frourios/frourio-go/tests/apps/basic/api/files/path"
	forms "github.com/frourios/frourio-go/tests/apps/basic/api/forms"
	mw "github.com/frourios/frourio-go/tests/apps/basic/api/mw"
	nest "github.com/frourios/frourio-go/tests/apps/basic/api/nest"
	nestChild "github.com/frourios/frourio-go/tests/apps/basic/api/nest/child"
	productsSale "github.com/frourios/frourio-go/tests/apps/basic/api/products/sale"
	public "github.com/frourios/frourio-go/tests/apps/basic/api/public"
	raw "github.com/frourios/frourio-go/tests/apps/basic/api/raw"
	secure "github.com/frourios/frourio-go/tests/apps/basic/api/secure"
	secureAdmin "github.com/frourios/frourio-go/tests/apps/basic/api/secure/admin"
	secureAdminUsers "github.com/frourios/frourio-go/tests/apps/basic/api/secure/admin/users"
	users "github.com/frourios/frourio-go/tests/apps/basic/api/users"
	usersUserid "github.com/frourios/frourio-go/tests/apps/basic/api/users/userid"
	usersUseridPostsPostid "github.com/frourios/frourio-go/tests/apps/basic/api/users/userid/posts/postid"
	"github.com/go-playground/validator/v10"
)

var frourioValidate = validator.New()

type Option func(*serverOptions)

type serverOptions struct{}

func Mount(mux *http.ServeMux, options ...Option) {
	mux.Handle("GET /", wrapGet(Route))
	mux.Handle("GET /auth", wrapAuthGet(auth.Route))
	mux.Handle("GET /blog/{slug...}", wrapBlogSlugGet(blogSlug.Route))
	mux.Handle("GET /files", wrapFilesPathGet(filesPath.Route))
	mux.Handle("GET /files/{path...}", wrapFilesPathGet(filesPath.Route))
	mux.Handle("GET /forms", wrapFormsGet(forms.Route))
	mux.Handle("POST /forms", wrapFormsPost(forms.Route))
	mux.Handle("PUT /forms", wrapFormsPut(forms.Route))
	mux.Handle("PATCH /forms", wrapFormsPatch(forms.Route))
	mux.Handle("DELETE /forms", wrapFormsDelete(forms.Route))
	mux.Handle("GET /mw", wrapMwGet(mw.Route))
	mux.Handle("GET /nest/child", wrapNestChildGet(nestChild.Route))
	mux.Handle("GET /products/セール品", wrapProductsSaleGet(productsSale.Route))
	mux.Handle("GET /public", wrapPublicGet(public.Route))
	mux.Handle("GET /raw", wrapRawGet(raw.Route))
	mux.Handle("GET /secure", wrapSecureGet(secure.Route))
	mux.Handle("GET /secure/admin", wrapSecureAdminGet(secureAdmin.Route))
	mux.Handle("POST /secure/admin", wrapSecureAdminPost(secureAdmin.Route))
	mux.Handle("GET /secure/admin/users", wrapSecureAdminUsersGet(secureAdminUsers.Route))
	mux.Handle("GET /users", wrapUsersGet(users.Route))
	mux.Handle("POST /users", wrapUsersPost(users.Route))
	mux.Handle("GET /users/{userid}", wrapUsersUseridGet(usersUserid.Route))
	mux.Handle("GET /users/{userid}/posts/{postid}", wrapUsersUseridPostsPostidGet(usersUseridPostsPostid.Route))
}

func Handler(options ...Option) http.Handler {
	mux := http.NewServeMux()
	Mount(mux, options...)
	return mux
}

func wrapGet(route RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := GetRequest{}
		query, err := decodeGetQuery(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"query"}, Message: err.Error()}})
			return
		}
		req.Query = query
		if err := frourioValidate.Struct(req.Query); err != nil {
			writeValidationError(w, err, "query")
			return
		}

		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeGetQuery(r *http.Request) (GetQuery, error) {
	var query GetQuery
	values := r.URL.Query()
	if vals, ok := values["search"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			query.Search = &val
		}
	}
	if vals, ok := values["limit"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			v, err := decodeInt(val)
			if err != nil {
				return query, err
			}
			query.Limit = &v
		}
	}
	if vals, ok := values["RawName"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			query.RawName = &val
		}
	}
	if vals, ok := values["active"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			v, err := decodeBool(val)
			if err != nil {
				return query, err
			}
			query.Active = &v
		}
	}
	if vals, ok := values["score"]; ok {
		parsed := make([]float64, 0, len(vals))
		for _, val := range vals {
			v, err := decodeFloat64(val)
			if err != nil {
				return query, err
			}
			parsed = append(parsed, v)
		}
		query.Scores = parsed
	}
	return query, nil
}

func wrapAuthGet(route auth.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := auth.GetRequest{}
		middleware := handlers.Middleware
		runHandler := func(ctx context.Context, methodState auth.GetContext) (auth.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState auth.MiddlewareContext) (auth.GetResponse, error) {
			return runHandler(ctx, auth.GetContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState auth.MiddlewareContext) (auth.GetResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context, allCtx auth.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.MiddlewareAllContext = allCtx
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(auth.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		res, err := runCurrentAll(r.Context(), auth.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case auth.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapBlogSlugGet(route blogSlug.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := blogSlug.GetRequest{}
		params, paramErr := decodeBlogSlugGetParams(r)
		if paramErr != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"params", paramErr.Field}, Message: paramErr.Message}})
			return
		}
		req.Params = params
		if err := frourioValidate.Struct(req.Params); err != nil {
			writeValidationError(w, err, "params")
			return
		}

		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case blogSlug.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeBlogSlugGetParams(r *http.Request) (blogSlug.Params, *frourioParamDecodeError) {
	var params blogSlug.Params
	{
		val := r.PathValue("slug")
		if val == "" {
			return params, &frourioParamDecodeError{Field: "slug", Message: "missing path parameter"}
		}
		vals := strings.Split(val, "/")
		params.Slug = vals
	}
	return params, nil
}

func wrapFilesPathGet(route filesPath.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := filesPath.GetRequest{}
		params, paramErr := decodeFilesPathGetParams(r)
		if paramErr != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"params", paramErr.Field}, Message: paramErr.Message}})
			return
		}
		req.Params = params

		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case filesPath.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeFilesPathGetParams(r *http.Request) (filesPath.Params, *frourioParamDecodeError) {
	var params filesPath.Params
	{
		val := r.PathValue("path")
		if val != "" {
			vals := strings.Split(val, "/")
			params.Path = &vals
		}
	}
	return params, nil
}

func wrapFormsGet(route forms.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := forms.GetRequest{}
		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case forms.GetStatus200:
			w.Header().Set("content-type", fmt.Sprint(v.Header.ContentType))
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, false)
		default:
			writeInternalError(w)
		}
	})
}

func wrapFormsPost(route forms.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Post == nil {
			http.NotFound(w, r)
			return
		}

		req := forms.PostRequest{}
		body, err := decodeFormsPostBody(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"body"}, Message: err.Error()}})
			return
		}
		req.Body = body
		if err := frourioValidate.Struct(req.Body); err != nil {
			writeValidationError(w, err, "body")
			return
		}

		res, err := handlers.Post(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case forms.PostStatus201:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeFormsPostBody(r *http.Request) (forms.FormPostBody, error) {
	var body forms.FormPostBody
	if err := r.ParseForm(); err != nil {
		return body, err
	}
	values := r.PostForm
	if vals, ok := values["name"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			body.Name = val
		}
	}
	if vals, ok := values["Alias"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			body.Alias = val
		}
	}
	if vals, ok := values["age"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			v, err := decodeInt(val)
			if err != nil {
				return body, err
			}
			body.Age = v
		}
	}
	if vals, ok := values["active"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			v, err := decodeBool(val)
			if err != nil {
				return body, err
			}
			body.Active = v
		}
	}
	if vals, ok := values["score"]; ok {
		parsed := make([]float64, 0, len(vals))
		for _, val := range vals {
			v, err := decodeFloat64(val)
			if err != nil {
				return body, err
			}
			parsed = append(parsed, v)
		}
		body.Scores = parsed
	}
	return body, nil
}

func wrapFormsPut(route forms.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Put == nil {
			http.NotFound(w, r)
			return
		}

		req := forms.PutRequest{}
		body, err := decodeFormsPutBody(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"body"}, Message: err.Error()}})
			return
		}
		req.Body = body
		if err := frourioValidate.Struct(req.Body); err != nil {
			writeValidationError(w, err, "body")
			return
		}

		res, err := handlers.Put(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case forms.PutStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeFormsPutBody(r *http.Request) (forms.PutBody, error) {
	var body forms.PutBody
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		return body, err
	}
	values := r.MultipartForm.Value
	if vals, ok := values["title"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			body.Title = val
		}
	}
	if vals, ok := values["count"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			v, err := decodeUint8(val)
			if err != nil {
				return body, err
			}
			body.Count = v
		}
	}
	return body, nil
}

func wrapFormsPatch(route forms.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Patch == nil {
			http.NotFound(w, r)
			return
		}

		req := forms.PatchRequest{}
		res, err := handlers.Patch(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case forms.PatchStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeBytes(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapFormsDelete(route forms.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Delete == nil {
			http.NotFound(w, r)
			return
		}

		req := forms.DeleteRequest{}
		res, err := handlers.Delete(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case forms.DeleteStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeMultipart(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapMwGet(route mw.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := mw.GetRequest{}
		middleware := handlers.Middleware
		runHandler := func(ctx context.Context, methodState mw.GetContext) (mw.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState mw.MiddlewareContext) (mw.GetResponse, error) {
			if middleware.Get != nil {
				return middleware.Get(ctx, r, req, mwState, func(ctx context.Context, req mw.GetRequest, methodCtx mw.GetMiddlewareContext) (mw.GetResponse, error) {
					if err := frourioValidate.Struct(methodCtx); err != nil {
						return nil, err
					}
					return runHandler(ctx, mw.GetContext{MiddlewareContext: mwState, GetMiddlewareContext: methodCtx})
				})
			}
			return runHandler(ctx, mw.GetContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState mw.MiddlewareContext) (mw.GetResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context) (any, error) {
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mw.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		res, err := runCurrentAll(r.Context(), mw.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case mw.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		case mw.GetStatus403:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapNestChildGet(route nestChild.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := nestChild.GetRequest{}
		ancestorHandlers0 := nest.Route.Handlers()
		runHandler := func(ctx context.Context, methodState nestChild.GetContext) (nestChild.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState nestChild.MiddlewareContext) (nestChild.GetResponse, error) {
			return runHandler(ctx, nestChild.GetContext{MiddlewareContext: mwState})
		}
		runAncestorAll0 := func(ctx context.Context, mwState nestChild.MiddlewareContext) (nestChild.GetResponse, error) {
			if ancestorHandlers0.Middleware.All != nil {
				res, err := ancestorHandlers0.Middleware.All(ctx, r, func(ctx context.Context, allCtx nest.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.TraceID = allCtx.TraceID
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(nestChild.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		res, err := runAncestorAll0(r.Context(), nestChild.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case nestChild.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapProductsSaleGet(route productsSale.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := productsSale.GetRequest{}
		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case productsSale.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapPublicGet(route public.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := public.GetRequest{}
		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case public.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapRawGet(route raw.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := raw.GetRequest{}
		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		if err := res.WriteHTTP(w, r); err != nil {
			writeInternalError(w)
		}
	})
}

func wrapSecureGet(route secure.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := secure.GetRequest{}
		middleware := handlers.Middleware
		runHandler := func(ctx context.Context, methodState secure.GetContext) (secure.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState secure.MiddlewareContext) (secure.GetResponse, error) {
			return runHandler(ctx, secure.GetContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState secure.MiddlewareContext) (secure.GetResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context, allCtx secure.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.MiddlewareAllContext = allCtx
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(secure.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		res, err := runCurrentAll(r.Context(), secure.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case secure.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapSecureAdminGet(route secureAdmin.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := secureAdmin.GetRequest{}
		middleware := handlers.Middleware
		ancestorHandlers0 := secure.Route.Handlers()
		runHandler := func(ctx context.Context, methodState secureAdmin.GetContext) (secureAdmin.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState secureAdmin.MiddlewareContext) (secureAdmin.GetResponse, error) {
			return runHandler(ctx, secureAdmin.GetContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState secureAdmin.MiddlewareContext) (secureAdmin.GetResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context, allCtx secureAdmin.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.MiddlewareAllContext = allCtx
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(secureAdmin.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		runAncestorAll0 := func(ctx context.Context, mwState secureAdmin.MiddlewareContext) (secureAdmin.GetResponse, error) {
			if ancestorHandlers0.Middleware.All != nil {
				res, err := ancestorHandlers0.Middleware.All(ctx, r, func(ctx context.Context, allCtx secure.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.UserID = allCtx.UserID
					mwState.TraceID = allCtx.TraceID
					return runCurrentAll(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(secureAdmin.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runCurrentAll(ctx, mwState)
		}
		res, err := runAncestorAll0(r.Context(), secureAdmin.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case secureAdmin.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapSecureAdminPost(route secureAdmin.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Post == nil {
			http.NotFound(w, r)
			return
		}

		req := secureAdmin.PostRequest{}
		body, err := decodeSecureAdminPostBody(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"body"}, Message: err.Error()}})
			return
		}
		req.Body = body
		if err := frourioValidate.Struct(req.Body); err != nil {
			writeValidationError(w, err, "body")
			return
		}

		middleware := handlers.Middleware
		ancestorHandlers0 := secure.Route.Handlers()
		runHandler := func(ctx context.Context, methodState secureAdmin.PostContext) (secureAdmin.PostResponse, error) {
			return handlers.Post(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState secureAdmin.MiddlewareContext) (secureAdmin.PostResponse, error) {
			if middleware.Post != nil {
				return middleware.Post(ctx, r, req, mwState, func(ctx context.Context, req secureAdmin.PostRequest) (secureAdmin.PostResponse, error) {
					return runHandler(ctx, secureAdmin.PostContext{MiddlewareContext: mwState})
				})
			}
			return runHandler(ctx, secureAdmin.PostContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState secureAdmin.MiddlewareContext) (secureAdmin.PostResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context, allCtx secureAdmin.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.MiddlewareAllContext = allCtx
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(secureAdmin.PostResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		runAncestorAll0 := func(ctx context.Context, mwState secureAdmin.MiddlewareContext) (secureAdmin.PostResponse, error) {
			if ancestorHandlers0.Middleware.All != nil {
				res, err := ancestorHandlers0.Middleware.All(ctx, r, func(ctx context.Context, allCtx secure.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.UserID = allCtx.UserID
					mwState.TraceID = allCtx.TraceID
					return runCurrentAll(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(secureAdmin.PostResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runCurrentAll(ctx, mwState)
		}
		res, err := runAncestorAll0(r.Context(), secureAdmin.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case secureAdmin.PostStatus201:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		case secureAdmin.PostStatus403:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeSecureAdminPostBody(r *http.Request) (secureAdmin.PostBody, error) {
	var body secureAdmin.PostBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		return body, err
	}
	return body, nil
}

func wrapSecureAdminUsersGet(route secureAdminUsers.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := secureAdminUsers.GetRequest{}
		query, err := decodeSecureAdminUsersGetQuery(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"query"}, Message: err.Error()}})
			return
		}
		req.Query = query
		if err := frourioValidate.Struct(req.Query); err != nil {
			writeValidationError(w, err, "query")
			return
		}

		ancestorHandlers0 := secure.Route.Handlers()
		ancestorHandlers1 := secureAdmin.Route.Handlers()
		runHandler := func(ctx context.Context, methodState secureAdminUsers.GetContext) (secureAdminUsers.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState secureAdminUsers.MiddlewareContext) (secureAdminUsers.GetResponse, error) {
			return runHandler(ctx, secureAdminUsers.GetContext{MiddlewareContext: mwState})
		}
		runAncestorAll1 := func(ctx context.Context, mwState secureAdminUsers.MiddlewareContext) (secureAdminUsers.GetResponse, error) {
			if ancestorHandlers1.Middleware.All != nil {
				res, err := ancestorHandlers1.Middleware.All(ctx, r, func(ctx context.Context, allCtx secureAdmin.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.IsAdmin = allCtx.IsAdmin
					mwState.Permissions = allCtx.Permissions
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(secureAdminUsers.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		runAncestorAll0 := func(ctx context.Context, mwState secureAdminUsers.MiddlewareContext) (secureAdminUsers.GetResponse, error) {
			if ancestorHandlers0.Middleware.All != nil {
				res, err := ancestorHandlers0.Middleware.All(ctx, r, func(ctx context.Context, allCtx secure.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.UserID = allCtx.UserID
					mwState.TraceID = allCtx.TraceID
					return runAncestorAll1(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(secureAdminUsers.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runAncestorAll1(ctx, mwState)
		}
		res, err := runAncestorAll0(r.Context(), secureAdminUsers.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case secureAdminUsers.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeSecureAdminUsersGetQuery(r *http.Request) (secureAdminUsers.GetQuery, error) {
	var query secureAdminUsers.GetQuery
	values := r.URL.Query()
	if vals, ok := values["role"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			query.Role = &val
		}
	}
	return query, nil
}

func wrapUsersGet(route users.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := users.GetRequest{}
		query, err := decodeUsersGetQuery(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"query"}, Message: err.Error()}})
			return
		}
		req.Query = query
		if err := frourioValidate.Struct(req.Query); err != nil {
			writeValidationError(w, err, "query")
			return
		}

		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case users.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeJSON(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeUsersGetQuery(r *http.Request) (users.GetQuery, error) {
	var query users.GetQuery
	values := r.URL.Query()
	if vals, ok := values["limit"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			v, err := decodeInt(val)
			if err != nil {
				return query, err
			}
			query.Limit = &v
		}
	}
	return query, nil
}

func wrapUsersPost(route users.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Post == nil {
			http.NotFound(w, r)
			return
		}

		req := users.PostRequest{}
		body, err := decodeUsersPostBody(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"body"}, Message: err.Error()}})
			return
		}
		req.Body = body
		if err := frourioValidate.Struct(req.Body); err != nil {
			writeValidationError(w, err, "body")
			return
		}

		res, err := handlers.Post(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case users.PostStatus201:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		case users.PostStatus400:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeUsersPostBody(r *http.Request) (users.PostBody, error) {
	var body users.PostBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		return body, err
	}
	return body, nil
}

func wrapUsersUseridGet(route usersUserid.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := usersUserid.GetRequest{}
		params, paramErr := decodeUsersUseridGetParams(r)
		if paramErr != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"params", paramErr.Field}, Message: paramErr.Message}})
			return
		}
		req.Params = params
		if err := frourioValidate.Struct(req.Params); err != nil {
			writeValidationError(w, err, "params")
			return
		}

		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case usersUserid.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		case usersUserid.GetStatus404:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeUsersUseridGetParams(r *http.Request) (usersUserid.Params, *frourioParamDecodeError) {
	var params usersUserid.Params
	{
		val := r.PathValue("userid")
		if val == "" {
			return params, &frourioParamDecodeError{Field: "userid", Message: "missing path parameter"}
		}
		v, err := strconv.Atoi(val)
		if err != nil {
			return params, &frourioParamDecodeError{Field: "userid", Message: "invalid int"}
		}
		params.Userid = v
	}
	return params, nil
}

func wrapUsersUseridPostsPostidGet(route usersUseridPostsPostid.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := usersUseridPostsPostid.GetRequest{}
		params, paramErr := decodeUsersUseridPostsPostidGetParams(r)
		if paramErr != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"params", paramErr.Field}, Message: paramErr.Message}})
			return
		}
		req.Params = params
		if err := frourioValidate.Struct(req.Params); err != nil {
			writeValidationError(w, err, "params")
			return
		}

		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case usersUseridPostsPostid.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeUsersUseridPostsPostidGetParams(r *http.Request) (usersUseridPostsPostid.Params, *frourioParamDecodeError) {
	var params usersUseridPostsPostid.Params
	{
		val := r.PathValue("userid")
		if val == "" {
			return params, &frourioParamDecodeError{Field: "userid", Message: "missing path parameter"}
		}
		v, err := strconv.Atoi(val)
		if err != nil {
			return params, &frourioParamDecodeError{Field: "userid", Message: "invalid int"}
		}
		params.Userid = v
	}
	{
		val := r.PathValue("postid")
		if val == "" {
			return params, &frourioParamDecodeError{Field: "postid", Message: "missing path parameter"}
		}
		params.Postid = val
	}
	return params, nil
}

type frourioError struct {
	Error  string         `json:"error"`
	Issues []frourioIssue `json:"issues,omitempty"`
	Status int            `json:"status"`
}

type frourioIssue struct {
	Message string `json:"message"`
	Path    []any  `json:"path"`
}

type frourioParamDecodeError struct {
	Field   string
	Message string
}

func (e *frourioParamDecodeError) Error() string {
	return e.Message
}

func writeValidationError(w http.ResponseWriter, err error, root string) {
	issues := []frourioIssue{}
	if validationErrors, ok := err.(validator.ValidationErrors); ok {
		for _, validationError := range validationErrors {
			issues = append(issues, frourioIssue{
				Path:    []any{root, validationError.Field()},
				Message: validationError.Tag(),
			})
		}
	} else {
		issues = append(issues, frourioIssue{Path: []any{root}, Message: err.Error()})
	}
	writeRequestError(w, issues)
}

func writeRequestError(w http.ResponseWriter, issues []frourioIssue) {
	writeJSON(w, http.StatusUnprocessableEntity, frourioError{
		Status: http.StatusUnprocessableEntity,
		Error:  "Unprocessable Entity",
		Issues: issues,
	}, true)
}

func writeInternalError(w http.ResponseWriter) {
	writeJSON(w, http.StatusInternalServerError, frourioError{
		Status: http.StatusInternalServerError,
		Error:  "Internal Server Error",
	}, true)
}

func writeJSON(w http.ResponseWriter, status int, body any, autoContentType bool) {
	if autoContentType {
		w.Header().Set("content-type", "application/json")
	}
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeText(w http.ResponseWriter, status int, body string, autoContentType bool) {
	if autoContentType {
		w.Header().Set("content-type", "text/plain; charset=utf-8")
	}
	w.WriteHeader(status)
	_, _ = w.Write([]byte(body))
}

func writeBytes(w http.ResponseWriter, status int, body []byte, autoContentType bool) {
	if autoContentType {
		w.Header().Set("content-type", "application/octet-stream")
	}
	w.WriteHeader(status)
	_, _ = w.Write(body)
}

func writeMultipart(w http.ResponseWriter, status int, body any, autoContentType bool) {
	writer := multipart.NewWriter(w)
	if autoContentType {
		w.Header().Set("content-type", writer.FormDataContentType())
	}
	w.WriteHeader(status)
	defer func() { _ = writer.Close() }()
	writeMultipartFields(writer, body)
}

func writeMultipartFields(writer *multipart.Writer, body any) {
	val := reflect.ValueOf(body)
	if val.Kind() == reflect.Pointer {
		if val.IsNil() {
			return
		}
		val = val.Elem()
	}
	if val.Kind() != reflect.Struct {
		_ = writer.WriteField("body", fmt.Sprint(body))
		return
	}
	typ := val.Type()
	for i := range val.NumField() {
		field := typ.Field(i)
		if field.PkgPath != "" {
			continue
		}
		key := field.Name
		if tag := field.Tag.Get("json"); tag != "" {
			key = strings.Split(tag, ",")[0]
			if key == "-" {
				continue
			}
			if key == "" {
				key = field.Name
			}
		}
		value := val.Field(i)
		if value.Kind() == reflect.Slice && value.Type().Elem().Kind() != reflect.Uint8 {
			for j := range value.Len() {
				_ = writer.WriteField(key, fmt.Sprint(value.Index(j).Interface()))
			}
			continue
		}
		_ = writer.WriteField(key, fmt.Sprint(value.Interface()))
	}
}

func decodeInt(val string) (int, error) {
	v, err := strconv.ParseInt(val, 10, 0)
	return int(v), err
}

func decodeInt8(val string) (int8, error) {
	v, err := strconv.ParseInt(val, 10, 8)
	return int8(v), err
}

func decodeInt16(val string) (int16, error) {
	v, err := strconv.ParseInt(val, 10, 16)
	return int16(v), err
}

func decodeInt32(val string) (int32, error) {
	v, err := strconv.ParseInt(val, 10, 32)
	return int32(v), err
}

func decodeInt64(val string) (int64, error) {
	return strconv.ParseInt(val, 10, 64)
}

func decodeUint(val string) (uint, error) {
	v, err := strconv.ParseUint(val, 10, 0)
	return uint(v), err
}

func decodeUint8(val string) (uint8, error) {
	v, err := strconv.ParseUint(val, 10, 8)
	return uint8(v), err
}

func decodeUint16(val string) (uint16, error) {
	v, err := strconv.ParseUint(val, 10, 16)
	return uint16(v), err
}

func decodeUint32(val string) (uint32, error) {
	v, err := strconv.ParseUint(val, 10, 32)
	return uint32(v), err
}

func decodeUint64(val string) (uint64, error) {
	return strconv.ParseUint(val, 10, 64)
}

func decodeFloat32(val string) (float32, error) {
	v, err := strconv.ParseFloat(val, 32)
	return float32(v), err
}

func decodeFloat64(val string) (float64, error) {
	return strconv.ParseFloat(val, 64)
}

func decodeBool(val string) (bool, error) {
	return strconv.ParseBool(val)
}

var _ = context.Background
var _ = fmt.Sprint
var _ = multipart.NewWriter
var _ = reflect.ValueOf
var _ = strconv.Itoa
var _ = strings.Split
