// Code generated by frourio-go. DO NOT EDIT.

package nest

import "context"

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type MiddlewareAllContext struct {
	TraceID string `json:"traceId" validate:"required"`
}

type MiddlewareContext struct {
	MiddlewareAllContext
}

type MiddlewareNext func(context.Context, MiddlewareAllContext) (any, error)
type MiddlewareAll func(context.Context, MiddlewareNext) (any, error)

type RouteMiddleware struct {
	All MiddlewareAll
}

type RouteHandlers struct {
	Middleware RouteMiddleware
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
