// Code generated by frourio-go. DO NOT EDIT.

package forms

import "context"

type RouteDefinition struct {
	handlers RouteHandlers
	spec     routeMetadata
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type PostRequest struct {
	Body PostBody
}

type PostBody struct {
	Name   string    `json:"name" validate:"required"`
	Age    int       `json:"age" validate:"gte=1"`
	Active bool      `json:"active"`
	Scores []float64 `json:"score" validate:"required"`
}

type PostResponse interface {
	isPostResponse()
	StatusCode() int
}

type PostStatus201 struct {
	Body string `json:"body" validate:"required"`
}

func (PostStatus201) isPostResponse() {}
func (PostStatus201) StatusCode() int { return 201 }

type PutRequest struct {
	Body PutBody
}

type PutBody struct {
	Title string `json:"title" validate:"required"`
	Count uint8  `json:"count" validate:"gte=1"`
}

type PutResponse interface {
	isPutResponse()
	StatusCode() int
}

type PutStatus200 struct {
	Body string `json:"body" validate:"required"`
}

func (PutStatus200) isPutResponse()  {}
func (PutStatus200) StatusCode() int { return 200 }

type RouteHandlers struct {
	Post func(context.Context, PostRequest) (PostResponse, error)
	Put  func(context.Context, PutRequest) (PutResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{handlers: handlers, spec: routeSpec}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
