// Code generated by frourio-go. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"reflect"
	"strconv"
	"strings"

	mw "github.com/frourios/frourio-go/tests/apps/middleware/api/mw"
	mwAdmin "github.com/frourios/frourio-go/tests/apps/middleware/api/mw/admin"
	mwAdminUsers "github.com/frourios/frourio-go/tests/apps/middleware/api/mw/admin/users"
	public "github.com/frourios/frourio-go/tests/apps/middleware/api/public"
	"github.com/go-playground/validator/v10"
)

var frourioValidate = validator.New()

type Option func(*serverOptions)

type serverOptions struct{}

func Mount(mux *http.ServeMux, options ...Option) {
	mux.Handle("GET /api", wrapGet(Route))
	mux.Handle("GET /api/mw", wrapMwGet(mw.Route))
	mux.Handle("GET /api/mw/admin", wrapMwAdminGet(mwAdmin.Route))
	mux.Handle("POST /api/mw/admin", wrapMwAdminPost(mwAdmin.Route))
	mux.Handle("GET /api/mw/admin/users", wrapMwAdminUsersGet(mwAdminUsers.Route))
	mux.Handle("GET /api/public", wrapPublicGet(public.Route))
}

func Handler(options ...Option) http.Handler {
	mux := http.NewServeMux()
	Mount(mux, options...)
	return mux
}

func wrapGet(route RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := GetRequest{}
		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeText(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapMwGet(route mw.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := mw.GetRequest{}
		middleware := handlers.Middleware
		runHandler := func(ctx context.Context, methodState mw.GetContext) (mw.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState mw.MiddlewareContext) (mw.GetResponse, error) {
			return runHandler(ctx, mw.GetContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState mw.MiddlewareContext) (mw.GetResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context, allCtx mw.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.MiddlewareAllContext = allCtx
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mw.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		res, err := runCurrentAll(r.Context(), mw.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case mw.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeJSON(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapMwAdminGet(route mwAdmin.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := mwAdmin.GetRequest{}
		middleware := handlers.Middleware
		ancestorHandlers0 := mw.Route.Handlers()
		runHandler := func(ctx context.Context, methodState mwAdmin.GetContext) (mwAdmin.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState mwAdmin.MiddlewareContext) (mwAdmin.GetResponse, error) {
			return runHandler(ctx, mwAdmin.GetContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState mwAdmin.MiddlewareContext) (mwAdmin.GetResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context, allCtx mwAdmin.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.MiddlewareAllContext = allCtx
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mwAdmin.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		runAncestorAll0 := func(ctx context.Context, mwState mwAdmin.MiddlewareContext) (mwAdmin.GetResponse, error) {
			if ancestorHandlers0.Middleware.All != nil {
				res, err := ancestorHandlers0.Middleware.All(ctx, r, func(ctx context.Context, allCtx mw.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.UserID = allCtx.UserID
					mwState.TraceID = allCtx.TraceID
					return runCurrentAll(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mwAdmin.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runCurrentAll(ctx, mwState)
		}
		res, err := runAncestorAll0(r.Context(), mwAdmin.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case mwAdmin.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeJSON(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func wrapMwAdminPost(route mwAdmin.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Post == nil {
			http.NotFound(w, r)
			return
		}

		req := mwAdmin.PostRequest{}
		body, err := decodeMwAdminPostBody(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"body"}, Message: err.Error()}})
			return
		}
		req.Body = body
		if err := frourioValidate.Struct(req.Body); err != nil {
			writeValidationError(w, err, "body")
			return
		}

		middleware := handlers.Middleware
		ancestorHandlers0 := mw.Route.Handlers()
		runHandler := func(ctx context.Context, methodState mwAdmin.PostContext) (mwAdmin.PostResponse, error) {
			return handlers.Post(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState mwAdmin.MiddlewareContext) (mwAdmin.PostResponse, error) {
			if middleware.Post != nil {
				return middleware.Post(ctx, r, req, mwState, func(ctx context.Context, req mwAdmin.PostRequest) (mwAdmin.PostResponse, error) {
					return runHandler(ctx, mwAdmin.PostContext{MiddlewareContext: mwState})
				})
			}
			return runHandler(ctx, mwAdmin.PostContext{MiddlewareContext: mwState})
		}
		runCurrentAll := func(ctx context.Context, mwState mwAdmin.MiddlewareContext) (mwAdmin.PostResponse, error) {
			if middleware.All != nil {
				res, err := middleware.All(ctx, r, func(ctx context.Context, allCtx mwAdmin.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.MiddlewareAllContext = allCtx
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mwAdmin.PostResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		runAncestorAll0 := func(ctx context.Context, mwState mwAdmin.MiddlewareContext) (mwAdmin.PostResponse, error) {
			if ancestorHandlers0.Middleware.All != nil {
				res, err := ancestorHandlers0.Middleware.All(ctx, r, func(ctx context.Context, allCtx mw.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.UserID = allCtx.UserID
					mwState.TraceID = allCtx.TraceID
					return runCurrentAll(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mwAdmin.PostResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runCurrentAll(ctx, mwState)
		}
		res, err := runAncestorAll0(r.Context(), mwAdmin.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case mwAdmin.PostStatus201:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeJSON(w, v.StatusCode(), v.Body, true)
		case mwAdmin.PostStatus403:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeJSON(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeMwAdminPostBody(r *http.Request) (mwAdmin.AdminPostBody, error) {
	var body mwAdmin.AdminPostBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		return body, err
	}
	return body, nil
}

func wrapMwAdminUsersGet(route mwAdminUsers.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := mwAdminUsers.GetRequest{}
		query, err := decodeMwAdminUsersGetQuery(r)
		if err != nil {
			writeRequestError(w, []frourioIssue{{Path: []any{"query"}, Message: err.Error()}})
			return
		}
		req.Query = query
		if err := frourioValidate.Struct(req.Query); err != nil {
			writeValidationError(w, err, "query")
			return
		}

		ancestorHandlers0 := mw.Route.Handlers()
		ancestorHandlers1 := mwAdmin.Route.Handlers()
		runHandler := func(ctx context.Context, methodState mwAdminUsers.GetContext) (mwAdminUsers.GetResponse, error) {
			return handlers.Get(ctx, req, methodState)
		}
		runMethod := func(ctx context.Context, mwState mwAdminUsers.MiddlewareContext) (mwAdminUsers.GetResponse, error) {
			return runHandler(ctx, mwAdminUsers.GetContext{MiddlewareContext: mwState})
		}
		runAncestorAll1 := func(ctx context.Context, mwState mwAdminUsers.MiddlewareContext) (mwAdminUsers.GetResponse, error) {
			if ancestorHandlers1.Middleware.All != nil {
				res, err := ancestorHandlers1.Middleware.All(ctx, r, func(ctx context.Context, allCtx mwAdmin.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.IsAdmin = allCtx.IsAdmin
					mwState.Permissions = allCtx.Permissions
					return runMethod(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mwAdminUsers.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runMethod(ctx, mwState)
		}
		runAncestorAll0 := func(ctx context.Context, mwState mwAdminUsers.MiddlewareContext) (mwAdminUsers.GetResponse, error) {
			if ancestorHandlers0.Middleware.All != nil {
				res, err := ancestorHandlers0.Middleware.All(ctx, r, func(ctx context.Context, allCtx mw.MiddlewareAllContext) (any, error) {
					if err := frourioValidate.Struct(allCtx); err != nil {
						return nil, err
					}
					mwState.UserID = allCtx.UserID
					mwState.TraceID = allCtx.TraceID
					return runAncestorAll1(ctx, mwState)
				})
				if err != nil {
					return nil, err
				}
				typed, ok := res.(mwAdminUsers.GetResponse)
				if !ok {
					return nil, fmt.Errorf("middleware returned invalid response")
				}
				return typed, nil
			}
			return runAncestorAll1(ctx, mwState)
		}
		res, err := runAncestorAll0(r.Context(), mwAdminUsers.MiddlewareContext{})
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case mwAdminUsers.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeJSON(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

func decodeMwAdminUsersGetQuery(r *http.Request) (mwAdminUsers.GetQuery, error) {
	var query mwAdminUsers.GetQuery
	values := r.URL.Query()
	if vals, ok := values["role"]; ok && len(vals) > 0 {
		val := vals[0]
		if val != "" {
			query.Role = &val
		}
	}
	return query, nil
}

func wrapPublicGet(route public.RouteDefinition) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handlers := route.Handlers()
		if handlers.Get == nil {
			http.NotFound(w, r)
			return
		}

		req := public.GetRequest{}
		res, err := handlers.Get(r.Context(), req)
		if err != nil {
			writeInternalError(w)
			return
		}
		if res == nil {
			writeInternalError(w)
			return
		}

		switch v := res.(type) {
		case public.GetStatus200:
			if err := frourioValidate.Struct(v); err != nil {
				writeInternalError(w)
				return
			}
			writeJSON(w, v.StatusCode(), v.Body, true)
		default:
			writeInternalError(w)
		}
	})
}

type frourioError struct {
	Error  string         `json:"error"`
	Issues []frourioIssue `json:"issues,omitempty"`
	Status int            `json:"status"`
}

type frourioIssue struct {
	Message string `json:"message"`
	Path    []any  `json:"path"`
}

func writeValidationError(w http.ResponseWriter, err error, root string) {
	issues := []frourioIssue{}
	if validationErrors, ok := err.(validator.ValidationErrors); ok {
		for _, validationError := range validationErrors {
			issues = append(issues, frourioIssue{
				Path:    []any{root, validationError.Field()},
				Message: validationError.Tag(),
			})
		}
	} else {
		issues = append(issues, frourioIssue{Path: []any{root}, Message: err.Error()})
	}
	writeRequestError(w, issues)
}

func writeRequestError(w http.ResponseWriter, issues []frourioIssue) {
	writeJSON(w, http.StatusUnprocessableEntity, frourioError{
		Status: http.StatusUnprocessableEntity,
		Error:  "Unprocessable Entity",
		Issues: issues,
	}, true)
}

func writeInternalError(w http.ResponseWriter) {
	writeJSON(w, http.StatusInternalServerError, frourioError{
		Status: http.StatusInternalServerError,
		Error:  "Internal Server Error",
	}, true)
}

func writeJSON(w http.ResponseWriter, status int, body any, autoContentType bool) {
	if autoContentType {
		w.Header().Set("content-type", "application/json")
	}
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeText(w http.ResponseWriter, status int, body string, autoContentType bool) {
	if autoContentType {
		w.Header().Set("content-type", "text/plain; charset=utf-8")
	}
	w.WriteHeader(status)
	_, _ = w.Write([]byte(body))
}

func writeBytes(w http.ResponseWriter, status int, body []byte, autoContentType bool) {
	if autoContentType {
		w.Header().Set("content-type", "application/octet-stream")
	}
	w.WriteHeader(status)
	_, _ = w.Write(body)
}

func writeMultipart(w http.ResponseWriter, status int, body any, autoContentType bool) {
	writer := multipart.NewWriter(w)
	if autoContentType {
		w.Header().Set("content-type", writer.FormDataContentType())
	}
	w.WriteHeader(status)
	defer func() { _ = writer.Close() }()
	writeMultipartFields(writer, body)
}

func writeMultipartFields(writer *multipart.Writer, body any) {
	val := reflect.ValueOf(body)
	if val.Kind() == reflect.Pointer {
		if val.IsNil() {
			return
		}
		val = val.Elem()
	}
	if val.Kind() != reflect.Struct {
		_ = writer.WriteField("body", fmt.Sprint(body))
		return
	}
	typ := val.Type()
	for i := range val.NumField() {
		field := typ.Field(i)
		if field.PkgPath != "" {
			continue
		}
		key := field.Name
		if tag := field.Tag.Get("json"); tag != "" {
			key = strings.Split(tag, ",")[0]
			if key == "-" {
				continue
			}
			if key == "" {
				key = field.Name
			}
		}
		value := val.Field(i)
		if value.Kind() == reflect.Slice && value.Type().Elem().Kind() != reflect.Uint8 {
			for j := range value.Len() {
				_ = writer.WriteField(key, fmt.Sprint(value.Index(j).Interface()))
			}
			continue
		}
		_ = writer.WriteField(key, fmt.Sprint(value.Interface()))
	}
}

func decodeInt(val string) (int, error) {
	v, err := strconv.ParseInt(val, 10, 0)
	return int(v), err
}

func decodeInt8(val string) (int8, error) {
	v, err := strconv.ParseInt(val, 10, 8)
	return int8(v), err
}

func decodeInt16(val string) (int16, error) {
	v, err := strconv.ParseInt(val, 10, 16)
	return int16(v), err
}

func decodeInt32(val string) (int32, error) {
	v, err := strconv.ParseInt(val, 10, 32)
	return int32(v), err
}

func decodeInt64(val string) (int64, error) {
	return strconv.ParseInt(val, 10, 64)
}

func decodeUint(val string) (uint, error) {
	v, err := strconv.ParseUint(val, 10, 0)
	return uint(v), err
}

func decodeUint8(val string) (uint8, error) {
	v, err := strconv.ParseUint(val, 10, 8)
	return uint8(v), err
}

func decodeUint16(val string) (uint16, error) {
	v, err := strconv.ParseUint(val, 10, 16)
	return uint16(v), err
}

func decodeUint32(val string) (uint32, error) {
	v, err := strconv.ParseUint(val, 10, 32)
	return uint32(v), err
}

func decodeUint64(val string) (uint64, error) {
	return strconv.ParseUint(val, 10, 64)
}

func decodeFloat32(val string) (float32, error) {
	v, err := strconv.ParseFloat(val, 32)
	return float32(v), err
}

func decodeFloat64(val string) (float64, error) {
	return strconv.ParseFloat(val, 64)
}

func decodeBool(val string) (bool, error) {
	return strconv.ParseBool(val)
}

var _ = context.Background
var _ = fmt.Sprint
var _ = multipart.NewWriter
var _ = reflect.ValueOf
var _ = strconv.Itoa
var _ = strings.Split
