// Code generated by frourio-go. DO NOT EDIT.

package mw

import "context"

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
}

type GetResponse interface {
	isGetResponse()
	StatusCode() int
}

type GetStatus200 struct {
	Body string `json:"body" validate:"required"`
}

func (GetStatus200) isGetResponse()  {}
func (GetStatus200) StatusCode() int { return 200 }

type GetStatus403 struct {
	Body string `json:"body" validate:"required"`
}

func (GetStatus403) isGetResponse()  {}
func (GetStatus403) StatusCode() int { return 403 }

type MiddlewareContext struct {
}

type MiddlewareNext func(context.Context) (any, error)
type MiddlewareAll func(context.Context, MiddlewareNext) (any, error)

type GetMiddlewareContext struct {
	Role string `json:"role" validate:"required"`
}

type GetContext struct {
	MiddlewareContext
	GetMiddlewareContext
}

type GetNext func(context.Context, GetRequest, GetMiddlewareContext) (GetResponse, error)
type GetMiddleware func(context.Context, GetRequest, MiddlewareContext, GetNext) (GetResponse, error)

type RouteMiddleware struct {
	All MiddlewareAll
	Get GetMiddleware
}

type RouteHandlers struct {
	Middleware RouteMiddleware
	Get        func(context.Context, GetRequest, GetContext) (GetResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
