// Package openapiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ApiAuthGetStatus200Body defines model for ApiAuthGetStatus200Body.
type ApiAuthGetStatus200Body = string

// ApiBlogSlugGetStatus200Body defines model for ApiBlogSlugGetStatus200Body.
type ApiBlogSlugGetStatus200Body = string

// ApiFilesPathGetStatus200Body defines model for ApiFilesPathGetStatus200Body.
type ApiFilesPathGetStatus200Body = string

// ApiFormsGetStatus200Body defines model for ApiFormsGetStatus200Body.
type ApiFormsGetStatus200Body = string

// ApiFormsPatchStatus200Body defines model for ApiFormsPatchStatus200Body.
type ApiFormsPatchStatus200Body = openapi_types.File

// ApiFormsPostStatus201Body defines model for ApiFormsPostStatus201Body.
type ApiFormsPostStatus201Body = string

// ApiFormsPutBody defines model for ApiFormsPutBody.
type ApiFormsPutBody struct {
	Count *int   `json:"count,omitempty"`
	Title string `json:"title"`
}

// ApiFormsPutStatus200Body defines model for ApiFormsPutStatus200Body.
type ApiFormsPutStatus200Body = string

// ApiGetStatus200Body defines model for ApiGetStatus200Body.
type ApiGetStatus200Body = string

// ApiMwGetStatus200Body defines model for ApiMwGetStatus200Body.
type ApiMwGetStatus200Body = string

// ApiMwGetStatus403Body defines model for ApiMwGetStatus403Body.
type ApiMwGetStatus403Body = string

// ApiNestChildGetStatus200Body defines model for ApiNestChildGetStatus200Body.
type ApiNestChildGetStatus200Body = string

// ApiProductsGetStatus200Body defines model for ApiProductsGetStatus200Body.
type ApiProductsGetStatus200Body = string

// ApiPublicGetStatus200Body defines model for ApiPublicGetStatus200Body.
type ApiPublicGetStatus200Body = string

// ApiSecureAdminGetStatus200Body defines model for ApiSecureAdminGetStatus200Body.
type ApiSecureAdminGetStatus200Body = string

// ApiSecureAdminPostBody defines model for ApiSecureAdminPostBody.
type ApiSecureAdminPostBody struct {
	Data string `json:"data"`
}

// ApiSecureAdminPostStatus201Body defines model for ApiSecureAdminPostStatus201Body.
type ApiSecureAdminPostStatus201Body = string

// ApiSecureAdminPostStatus403Body defines model for ApiSecureAdminPostStatus403Body.
type ApiSecureAdminPostStatus403Body = string

// ApiSecureAdminUsersGetStatus200Body defines model for ApiSecureAdminUsersGetStatus200Body.
type ApiSecureAdminUsersGetStatus200Body = string

// ApiSecureGetStatus200Body defines model for ApiSecureGetStatus200Body.
type ApiSecureGetStatus200Body = string

// ApiUsersGetStatus200Body defines model for ApiUsersGetStatus200Body.
type ApiUsersGetStatus200Body = []string

// ApiUsersPostBody defines model for ApiUsersPostBody.
type ApiUsersPostBody struct {
	Age  *int   `json:"age,omitempty"`
	Name string `json:"name"`
}

// ApiUsersPostStatus201Body defines model for ApiUsersPostStatus201Body.
type ApiUsersPostStatus201Body = string

// ApiUsersPostStatus400Body defines model for ApiUsersPostStatus400Body.
type ApiUsersPostStatus400Body = string

// ApiUsersUseridGetStatus200Body defines model for ApiUsersUseridGetStatus200Body.
type ApiUsersUseridGetStatus200Body = string

// ApiUsersUseridGetStatus404Body defines model for ApiUsersUseridGetStatus404Body.
type ApiUsersUseridGetStatus404Body = string

// FormsFormPostBody defines model for FormsFormPostBody.
type FormsFormPostBody struct {
	Alias  *string   `json:"Alias,omitempty"`
	Active *bool     `json:"active,omitempty"`
	Age    *int      `json:"age,omitempty"`
	Name   string    `json:"name"`
	Score  []float32 `json:"score"`
}

// FormsMultipartResponseBody defines model for FormsMultipartResponseBody.
type FormsMultipartResponseBody struct {
	Count *int    `json:"Count,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// FrourioError defines model for FrourioError.
type FrourioError struct {
	Error  *string `json:"error,omitempty"`
	Issues *[]struct {
		Message *string        `json:"message,omitempty"`
		Path    *[]interface{} `json:"path,omitempty"`
	} `json:"issues,omitempty"`
	Status *int `json:"status,omitempty"`
}

// GetApiParams defines parameters for GetApi.
type GetApiParams struct {
	// Search Search term
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Limit Maximum number of items.
	// 	Indented limit detail.
	Limit   *int      `form:"limit,omitempty" json:"limit,omitempty"`
	RawName *string   `form:"RawName,omitempty" json:"RawName,omitempty"`
	Active  *bool     `form:"active,omitempty" json:"active,omitempty"`
	Score   []float32 `form:"score" json:"score"`
}

// GetApiSecureAdminUsersParams defines parameters for GetApiSecureAdminUsers.
type GetApiSecureAdminUsersParams struct {
	Role *string `form:"role,omitempty" json:"role,omitempty"`
}

// GetApiUsersParams defines parameters for GetApiUsers.
type GetApiUsersParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostApiFormsFormdataRequestBody defines body for PostApiForms for application/x-www-form-urlencoded ContentType.
type PostApiFormsFormdataRequestBody = FormsFormPostBody

// PutApiFormsMultipartRequestBody defines body for PutApiForms for multipart/form-data ContentType.
type PutApiFormsMultipartRequestBody = ApiFormsPutBody

// PostApiSecureAdminJSONRequestBody defines body for PostApiSecureAdmin for application/json ContentType.
type PostApiSecureAdminJSONRequestBody = ApiSecureAdminPostBody

// PostApiUsersJSONRequestBody defines body for PostApiUsers for application/json ContentType.
type PostApiUsersJSONRequestBody = ApiUsersPostBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApi request
	GetApi(ctx context.Context, params *GetApiParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiAuth request
	GetApiAuth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiBlogBySlug request
	GetApiBlogBySlug(ctx context.Context, slug []string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiFiles request
	GetApiFiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiFilesByPath request
	GetApiFilesByPath(ctx context.Context, path []string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiForms request
	DeleteApiForms(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiForms request
	GetApiForms(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchApiForms request
	PatchApiForms(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiFormsWithBody request with any body
	PostApiFormsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiFormsWithFormdataBody(ctx context.Context, body PostApiFormsFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiFormsWithBody request with any body
	PutApiFormsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiMw request
	GetApiMw(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiNestChild request
	GetApiNestChild(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiProducts request
	GetApiProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiPublic request
	GetApiPublic(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiRaw request
	GetApiRaw(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiSecure request
	GetApiSecure(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiSecureAdmin request
	GetApiSecureAdmin(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiSecureAdminWithBody request with any body
	PostApiSecureAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiSecureAdmin(ctx context.Context, body PostApiSecureAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiSecureAdminUsers request
	GetApiSecureAdminUsers(ctx context.Context, params *GetApiSecureAdminUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiUsers request
	GetApiUsers(ctx context.Context, params *GetApiUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiUsersWithBody request with any body
	PostApiUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiUsers(ctx context.Context, body PostApiUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiUsersByUserid request
	GetApiUsersByUserid(ctx context.Context, userid int, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApi(ctx context.Context, params *GetApiParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiAuth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiAuthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiBlogBySlug(ctx context.Context, slug []string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiBlogBySlugRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiFiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiFilesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiFilesByPath(ctx context.Context, path []string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiFilesByPathRequest(c.Server, path)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiForms(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiFormsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiForms(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiFormsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchApiForms(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchApiFormsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiFormsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiFormsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiFormsWithFormdataBody(ctx context.Context, body PostApiFormsFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiFormsRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiFormsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiFormsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiMw(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiMwRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiNestChild(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiNestChildRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiProductsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiPublic(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiPublicRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiRaw(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiRawRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiSecure(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiSecureRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiSecureAdmin(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiSecureAdminRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiSecureAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiSecureAdminRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiSecureAdmin(ctx context.Context, body PostApiSecureAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiSecureAdminRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiSecureAdminUsers(ctx context.Context, params *GetApiSecureAdminUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiSecureAdminUsersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiUsers(ctx context.Context, params *GetApiUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiUsersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiUsersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiUsers(ctx context.Context, body PostApiUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiUsersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiUsersByUserid(ctx context.Context, userid int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiUsersByUseridRequest(c.Server, userid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiRequest generates requests for GetApi
func NewGetApiRequest(server string, params *GetApiParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Search != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "search", *params.Search, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.RawName != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "RawName", *params.RawName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Active != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "active", *params.Active, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Score != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "score", params.Score, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiAuthRequest generates requests for GetApiAuth
func NewGetApiAuthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/auth")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiBlogBySlugRequest generates requests for GetApiBlogBySlug
func NewGetApiBlogBySlugRequest(server string, slug []string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "slug", slug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "array", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/blog/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiFilesRequest generates requests for GetApiFiles
func NewGetApiFilesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiFilesByPathRequest generates requests for GetApiFilesByPath
func NewGetApiFilesByPathRequest(server string, path []string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "path", path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "array", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/files/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteApiFormsRequest generates requests for DeleteApiForms
func NewDeleteApiFormsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/forms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiFormsRequest generates requests for GetApiForms
func NewGetApiFormsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/forms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchApiFormsRequest generates requests for PatchApiForms
func NewPatchApiFormsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/forms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiFormsRequestWithFormdataBody calls the generic PostApiForms builder with application/x-www-form-urlencoded body
func NewPostApiFormsRequestWithFormdataBody(server string, body PostApiFormsFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostApiFormsRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostApiFormsRequestWithBody generates requests for PostApiForms with any type of body
func NewPostApiFormsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/forms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutApiFormsRequestWithBody generates requests for PutApiForms with any type of body
func NewPutApiFormsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/forms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiMwRequest generates requests for GetApiMw
func NewGetApiMwRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/mw")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiNestChildRequest generates requests for GetApiNestChild
func NewGetApiNestChildRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/nest/child")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiProductsRequest generates requests for GetApiProducts
func NewGetApiProductsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/products/セール品")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiPublicRequest generates requests for GetApiPublic
func NewGetApiPublicRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiRawRequest generates requests for GetApiRaw
func NewGetApiRawRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/raw")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiSecureRequest generates requests for GetApiSecure
func NewGetApiSecureRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/secure")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiSecureAdminRequest generates requests for GetApiSecureAdmin
func NewGetApiSecureAdminRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/secure/admin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiSecureAdminRequest calls the generic PostApiSecureAdmin builder with application/json body
func NewPostApiSecureAdminRequest(server string, body PostApiSecureAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiSecureAdminRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiSecureAdminRequestWithBody generates requests for PostApiSecureAdmin with any type of body
func NewPostApiSecureAdminRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/secure/admin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiSecureAdminUsersRequest generates requests for GetApiSecureAdminUsers
func NewGetApiSecureAdminUsersRequest(server string, params *GetApiSecureAdminUsersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/secure/admin/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Role != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "role", *params.Role, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiUsersRequest generates requests for GetApiUsers
func NewGetApiUsersRequest(server string, params *GetApiUsersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiUsersRequest calls the generic PostApiUsers builder with application/json body
func NewPostApiUsersRequest(server string, body PostApiUsersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiUsersRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiUsersRequestWithBody generates requests for PostApiUsers with any type of body
func NewPostApiUsersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiUsersByUseridRequest generates requests for GetApiUsersByUserid
func NewGetApiUsersByUseridRequest(server string, userid int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "userid", userid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiWithResponse request
	GetApiWithResponse(ctx context.Context, params *GetApiParams, reqEditors ...RequestEditorFn) (*GetApiResponse, error)

	// GetApiAuthWithResponse request
	GetApiAuthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiAuthResponse, error)

	// GetApiBlogBySlugWithResponse request
	GetApiBlogBySlugWithResponse(ctx context.Context, slug []string, reqEditors ...RequestEditorFn) (*GetApiBlogBySlugResponse, error)

	// GetApiFilesWithResponse request
	GetApiFilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiFilesResponse, error)

	// GetApiFilesByPathWithResponse request
	GetApiFilesByPathWithResponse(ctx context.Context, path []string, reqEditors ...RequestEditorFn) (*GetApiFilesByPathResponse, error)

	// DeleteApiFormsWithResponse request
	DeleteApiFormsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteApiFormsResponse, error)

	// GetApiFormsWithResponse request
	GetApiFormsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiFormsResponse, error)

	// PatchApiFormsWithResponse request
	PatchApiFormsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PatchApiFormsResponse, error)

	// PostApiFormsWithBodyWithResponse request with any body
	PostApiFormsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiFormsResponse, error)

	PostApiFormsWithFormdataBodyWithResponse(ctx context.Context, body PostApiFormsFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostApiFormsResponse, error)

	// PutApiFormsWithBodyWithResponse request with any body
	PutApiFormsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiFormsResponse, error)

	// GetApiMwWithResponse request
	GetApiMwWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiMwResponse, error)

	// GetApiNestChildWithResponse request
	GetApiNestChildWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiNestChildResponse, error)

	// GetApiProductsWithResponse request
	GetApiProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiProductsResponse, error)

	// GetApiPublicWithResponse request
	GetApiPublicWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiPublicResponse, error)

	// GetApiRawWithResponse request
	GetApiRawWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiRawResponse, error)

	// GetApiSecureWithResponse request
	GetApiSecureWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiSecureResponse, error)

	// GetApiSecureAdminWithResponse request
	GetApiSecureAdminWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiSecureAdminResponse, error)

	// PostApiSecureAdminWithBodyWithResponse request with any body
	PostApiSecureAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiSecureAdminResponse, error)

	PostApiSecureAdminWithResponse(ctx context.Context, body PostApiSecureAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiSecureAdminResponse, error)

	// GetApiSecureAdminUsersWithResponse request
	GetApiSecureAdminUsersWithResponse(ctx context.Context, params *GetApiSecureAdminUsersParams, reqEditors ...RequestEditorFn) (*GetApiSecureAdminUsersResponse, error)

	// GetApiUsersWithResponse request
	GetApiUsersWithResponse(ctx context.Context, params *GetApiUsersParams, reqEditors ...RequestEditorFn) (*GetApiUsersResponse, error)

	// PostApiUsersWithBodyWithResponse request with any body
	PostApiUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiUsersResponse, error)

	PostApiUsersWithResponse(ctx context.Context, body PostApiUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiUsersResponse, error)

	// GetApiUsersByUseridWithResponse request
	GetApiUsersByUseridWithResponse(ctx context.Context, userid int, reqEditors ...RequestEditorFn) (*GetApiUsersByUseridResponse, error)
}

type GetApiResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiAuthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiAuthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiAuthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiAuthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiBlogBySlugResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiBlogBySlugResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiBlogBySlugResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiBlogBySlugResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiFilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiFilesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiFilesByPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiFilesByPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiFilesByPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiFilesByPathResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteApiFormsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r DeleteApiFormsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiFormsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteApiFormsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiFormsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiFormsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiFormsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiFormsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchApiFormsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r PatchApiFormsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchApiFormsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchApiFormsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiFormsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r PostApiFormsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiFormsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiFormsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutApiFormsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r PutApiFormsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiFormsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutApiFormsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiMwResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiMwResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiMwResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiMwResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiNestChildResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiNestChildResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiNestChildResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiNestChildResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiProductsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiPublicResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiPublicResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiPublicResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiPublicResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiRawResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiRawResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiRawResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiRawResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiSecureResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiSecureResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiSecureResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiSecureResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiSecureAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiSecureAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiSecureAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiSecureAdminResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiSecureAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r PostApiSecureAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiSecureAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiSecureAdminResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiSecureAdminUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiSecureAdminUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiSecureAdminUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiSecureAdminUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiUsersGetStatus200Body
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r PostApiUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiUsersByUseridResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *FrourioError
}

// Status returns HTTPResponse.Status
func (r GetApiUsersByUseridResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiUsersByUseridResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiUsersByUseridResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiWithResponse request returning *GetApiResponse
func (c *ClientWithResponses) GetApiWithResponse(ctx context.Context, params *GetApiParams, reqEditors ...RequestEditorFn) (*GetApiResponse, error) {
	rsp, err := c.GetApi(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiResponse(rsp)
}

// GetApiAuthWithResponse request returning *GetApiAuthResponse
func (c *ClientWithResponses) GetApiAuthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiAuthResponse, error) {
	rsp, err := c.GetApiAuth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiAuthResponse(rsp)
}

// GetApiBlogBySlugWithResponse request returning *GetApiBlogBySlugResponse
func (c *ClientWithResponses) GetApiBlogBySlugWithResponse(ctx context.Context, slug []string, reqEditors ...RequestEditorFn) (*GetApiBlogBySlugResponse, error) {
	rsp, err := c.GetApiBlogBySlug(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiBlogBySlugResponse(rsp)
}

// GetApiFilesWithResponse request returning *GetApiFilesResponse
func (c *ClientWithResponses) GetApiFilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiFilesResponse, error) {
	rsp, err := c.GetApiFiles(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiFilesResponse(rsp)
}

// GetApiFilesByPathWithResponse request returning *GetApiFilesByPathResponse
func (c *ClientWithResponses) GetApiFilesByPathWithResponse(ctx context.Context, path []string, reqEditors ...RequestEditorFn) (*GetApiFilesByPathResponse, error) {
	rsp, err := c.GetApiFilesByPath(ctx, path, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiFilesByPathResponse(rsp)
}

// DeleteApiFormsWithResponse request returning *DeleteApiFormsResponse
func (c *ClientWithResponses) DeleteApiFormsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteApiFormsResponse, error) {
	rsp, err := c.DeleteApiForms(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiFormsResponse(rsp)
}

// GetApiFormsWithResponse request returning *GetApiFormsResponse
func (c *ClientWithResponses) GetApiFormsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiFormsResponse, error) {
	rsp, err := c.GetApiForms(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiFormsResponse(rsp)
}

// PatchApiFormsWithResponse request returning *PatchApiFormsResponse
func (c *ClientWithResponses) PatchApiFormsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PatchApiFormsResponse, error) {
	rsp, err := c.PatchApiForms(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchApiFormsResponse(rsp)
}

// PostApiFormsWithBodyWithResponse request with arbitrary body returning *PostApiFormsResponse
func (c *ClientWithResponses) PostApiFormsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiFormsResponse, error) {
	rsp, err := c.PostApiFormsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiFormsResponse(rsp)
}

func (c *ClientWithResponses) PostApiFormsWithFormdataBodyWithResponse(ctx context.Context, body PostApiFormsFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostApiFormsResponse, error) {
	rsp, err := c.PostApiFormsWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiFormsResponse(rsp)
}

// PutApiFormsWithBodyWithResponse request with arbitrary body returning *PutApiFormsResponse
func (c *ClientWithResponses) PutApiFormsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiFormsResponse, error) {
	rsp, err := c.PutApiFormsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiFormsResponse(rsp)
}

// GetApiMwWithResponse request returning *GetApiMwResponse
func (c *ClientWithResponses) GetApiMwWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiMwResponse, error) {
	rsp, err := c.GetApiMw(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiMwResponse(rsp)
}

// GetApiNestChildWithResponse request returning *GetApiNestChildResponse
func (c *ClientWithResponses) GetApiNestChildWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiNestChildResponse, error) {
	rsp, err := c.GetApiNestChild(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiNestChildResponse(rsp)
}

// GetApiProductsWithResponse request returning *GetApiProductsResponse
func (c *ClientWithResponses) GetApiProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiProductsResponse, error) {
	rsp, err := c.GetApiProducts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiProductsResponse(rsp)
}

// GetApiPublicWithResponse request returning *GetApiPublicResponse
func (c *ClientWithResponses) GetApiPublicWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiPublicResponse, error) {
	rsp, err := c.GetApiPublic(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiPublicResponse(rsp)
}

// GetApiRawWithResponse request returning *GetApiRawResponse
func (c *ClientWithResponses) GetApiRawWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiRawResponse, error) {
	rsp, err := c.GetApiRaw(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiRawResponse(rsp)
}

// GetApiSecureWithResponse request returning *GetApiSecureResponse
func (c *ClientWithResponses) GetApiSecureWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiSecureResponse, error) {
	rsp, err := c.GetApiSecure(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiSecureResponse(rsp)
}

// GetApiSecureAdminWithResponse request returning *GetApiSecureAdminResponse
func (c *ClientWithResponses) GetApiSecureAdminWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiSecureAdminResponse, error) {
	rsp, err := c.GetApiSecureAdmin(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiSecureAdminResponse(rsp)
}

// PostApiSecureAdminWithBodyWithResponse request with arbitrary body returning *PostApiSecureAdminResponse
func (c *ClientWithResponses) PostApiSecureAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiSecureAdminResponse, error) {
	rsp, err := c.PostApiSecureAdminWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiSecureAdminResponse(rsp)
}

func (c *ClientWithResponses) PostApiSecureAdminWithResponse(ctx context.Context, body PostApiSecureAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiSecureAdminResponse, error) {
	rsp, err := c.PostApiSecureAdmin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiSecureAdminResponse(rsp)
}

// GetApiSecureAdminUsersWithResponse request returning *GetApiSecureAdminUsersResponse
func (c *ClientWithResponses) GetApiSecureAdminUsersWithResponse(ctx context.Context, params *GetApiSecureAdminUsersParams, reqEditors ...RequestEditorFn) (*GetApiSecureAdminUsersResponse, error) {
	rsp, err := c.GetApiSecureAdminUsers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiSecureAdminUsersResponse(rsp)
}

// GetApiUsersWithResponse request returning *GetApiUsersResponse
func (c *ClientWithResponses) GetApiUsersWithResponse(ctx context.Context, params *GetApiUsersParams, reqEditors ...RequestEditorFn) (*GetApiUsersResponse, error) {
	rsp, err := c.GetApiUsers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiUsersResponse(rsp)
}

// PostApiUsersWithBodyWithResponse request with arbitrary body returning *PostApiUsersResponse
func (c *ClientWithResponses) PostApiUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiUsersResponse, error) {
	rsp, err := c.PostApiUsersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiUsersResponse(rsp)
}

func (c *ClientWithResponses) PostApiUsersWithResponse(ctx context.Context, body PostApiUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiUsersResponse, error) {
	rsp, err := c.PostApiUsers(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiUsersResponse(rsp)
}

// GetApiUsersByUseridWithResponse request returning *GetApiUsersByUseridResponse
func (c *ClientWithResponses) GetApiUsersByUseridWithResponse(ctx context.Context, userid int, reqEditors ...RequestEditorFn) (*GetApiUsersByUseridResponse, error) {
	rsp, err := c.GetApiUsersByUserid(ctx, userid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiUsersByUseridResponse(rsp)
}

// ParseGetApiResponse parses an HTTP response from a GetApiWithResponse call
func ParseGetApiResponse(rsp *http.Response) (*GetApiResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiAuthResponse parses an HTTP response from a GetApiAuthWithResponse call
func ParseGetApiAuthResponse(rsp *http.Response) (*GetApiAuthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiAuthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiBlogBySlugResponse parses an HTTP response from a GetApiBlogBySlugWithResponse call
func ParseGetApiBlogBySlugResponse(rsp *http.Response) (*GetApiBlogBySlugResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiBlogBySlugResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiFilesResponse parses an HTTP response from a GetApiFilesWithResponse call
func ParseGetApiFilesResponse(rsp *http.Response) (*GetApiFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiFilesByPathResponse parses an HTTP response from a GetApiFilesByPathWithResponse call
func ParseGetApiFilesByPathResponse(rsp *http.Response) (*GetApiFilesByPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiFilesByPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseDeleteApiFormsResponse parses an HTTP response from a DeleteApiFormsWithResponse call
func ParseDeleteApiFormsResponse(rsp *http.Response) (*DeleteApiFormsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiFormsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiFormsResponse parses an HTTP response from a GetApiFormsWithResponse call
func ParseGetApiFormsResponse(rsp *http.Response) (*GetApiFormsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiFormsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePatchApiFormsResponse parses an HTTP response from a PatchApiFormsWithResponse call
func ParsePatchApiFormsResponse(rsp *http.Response) (*PatchApiFormsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchApiFormsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePostApiFormsResponse parses an HTTP response from a PostApiFormsWithResponse call
func ParsePostApiFormsResponse(rsp *http.Response) (*PostApiFormsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiFormsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePutApiFormsResponse parses an HTTP response from a PutApiFormsWithResponse call
func ParsePutApiFormsResponse(rsp *http.Response) (*PutApiFormsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiFormsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiMwResponse parses an HTTP response from a GetApiMwWithResponse call
func ParseGetApiMwResponse(rsp *http.Response) (*GetApiMwResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiMwResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiNestChildResponse parses an HTTP response from a GetApiNestChildWithResponse call
func ParseGetApiNestChildResponse(rsp *http.Response) (*GetApiNestChildResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiNestChildResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiProductsResponse parses an HTTP response from a GetApiProductsWithResponse call
func ParseGetApiProductsResponse(rsp *http.Response) (*GetApiProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiPublicResponse parses an HTTP response from a GetApiPublicWithResponse call
func ParseGetApiPublicResponse(rsp *http.Response) (*GetApiPublicResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiPublicResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiRawResponse parses an HTTP response from a GetApiRawWithResponse call
func ParseGetApiRawResponse(rsp *http.Response) (*GetApiRawResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiRawResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiSecureResponse parses an HTTP response from a GetApiSecureWithResponse call
func ParseGetApiSecureResponse(rsp *http.Response) (*GetApiSecureResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiSecureResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiSecureAdminResponse parses an HTTP response from a GetApiSecureAdminWithResponse call
func ParseGetApiSecureAdminResponse(rsp *http.Response) (*GetApiSecureAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiSecureAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePostApiSecureAdminResponse parses an HTTP response from a PostApiSecureAdminWithResponse call
func ParsePostApiSecureAdminResponse(rsp *http.Response) (*PostApiSecureAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiSecureAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiSecureAdminUsersResponse parses an HTTP response from a GetApiSecureAdminUsersWithResponse call
func ParseGetApiSecureAdminUsersResponse(rsp *http.Response) (*GetApiSecureAdminUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiSecureAdminUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiUsersResponse parses an HTTP response from a GetApiUsersWithResponse call
func ParseGetApiUsersResponse(rsp *http.Response) (*GetApiUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiUsersGetStatus200Body
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePostApiUsersResponse parses an HTTP response from a PostApiUsersWithResponse call
func ParsePostApiUsersResponse(rsp *http.Response) (*PostApiUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiUsersByUseridResponse parses an HTTP response from a GetApiUsersByUseridWithResponse call
func ParseGetApiUsersByUseridResponse(rsp *http.Response) (*GetApiUsersByUseridResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiUsersByUseridResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest FrourioError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
