// Code generated by frourio-go. DO NOT EDIT.

package users

import "context"

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
	Query GetQuery
}

type GetQuery struct {
	Role *string `json:"role"`
}

type GetResponse interface {
	isGetResponse()
	StatusCode() int
}

type GetStatus200 struct {
	Body UsersResponseBody
}

func (GetStatus200) isGetResponse()  {}
func (GetStatus200) StatusCode() int { return 200 }

type MiddlewareContext struct {
	UserID      *string  `json:"userId"`
	TraceID     string   `json:"traceId" validate:"required"`
	IsAdmin     bool     `json:"isAdmin"`
	Permissions []string `json:"permissions"`
}

type GetContext struct {
	MiddlewareContext
}

type RouteMiddleware struct {
}

type RouteHandlers struct {
	Middleware RouteMiddleware
	Get        func(context.Context, GetRequest, GetContext) (GetResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
