package generator

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedHeader = "// Code generated by frourio-go. DO NOT EDIT.\n\n"

func Generate(opts Options) error {
	if opts.APIDir == "" {
		return fmt.Errorf("api dir is required")
	}

	apiDir, err := filepath.Abs(opts.APIDir)
	if err != nil {
		return err
	}

	routes, err := scan(apiDir)
	if err != nil {
		return err
	}
	if len(routes) == 0 {
		return fmt.Errorf("no frourio.go files found under %s", apiDir)
	}
	fillRoutePaths(routes)
	if err := fillImportInfo(apiDir, routes); err != nil {
		return err
	}
	fillAncestors(routes)

	sort.Slice(routes, func(i, j int) bool {
		return routes[i].URLPath < routes[j].URLPath
	})

	if !opts.OnlyOpenAPI {
		for _, route := range routes {
			if err := writeGoFile(filepath.Join(route.Dir, "frourio_relay.go"), relayText(route)); err != nil {
				return err
			}
		}

		if err := writeGoFile(filepath.Join(apiDir, "frourio_server.go"), serverText(apiDir, routes)); err != nil {
			return err
		}
	}

	openAPIPath := opts.OpenAPIPath
	if openAPIPath == "" {
		openAPIPath = filepath.Join(apiDir, "openapi.json")
	}
	if err := os.MkdirAll(filepath.Dir(openAPIPath), 0o755); err != nil {
		return err
	}

	doc := openAPIDocument(routes)
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(openAPIPath, append(data, '\n'), 0o644)
}

func fillAncestors(routes []RouteSpec) {
	for i := range routes {
		for _, candidate := range routes {
			if candidate.RelDir == routes[i].RelDir || !hasMiddleware(candidate) {
				continue
			}
			if isAncestorRel(candidate.RelDir, routes[i].RelDir) {
				routes[i].Ancestors = append(routes[i].Ancestors, candidate)
			}
		}
		sort.Slice(routes[i].Ancestors, func(a, b int) bool {
			return len(routes[i].Ancestors[a].RelDir) < len(routes[i].Ancestors[b].RelDir)
		})
	}
}

func isAncestorRel(parent, child string) bool {
	if parent == "" {
		return child != ""
	}
	return strings.HasPrefix(child, parent+"/")
}

func writeGoFile(path string, text string) error {
	formatted, err := format.Source([]byte(generatedHeader + text))
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func exportName(name string) string {
	if name == "" {
		return name
	}
	if strings.EqualFold(name, "body") {
		return "Body"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func lowerName(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func fillImportInfo(apiDir string, routes []RouteSpec) error {
	moduleRoot, modulePath, err := findModule(apiDir)
	if err != nil {
		return err
	}
	apiRel, err := filepath.Rel(moduleRoot, apiDir)
	if err != nil {
		return err
	}
	apiImport := modulePath + "/" + filepath.ToSlash(apiRel)

	usedAliases := map[string]int{}
	for i := range routes {
		rel := routes[i].RelDir
		if routes[i].RelDir == "" {
			routes[i].ImportPath = apiImport
			routes[i].Alias = ""
			continue
		}
		routes[i].ImportPath = apiImport + "/" + rel
		alias := routeAlias(rel)
		usedAliases[alias]++
		if usedAliases[alias] > 1 {
			alias = fmt.Sprintf("%s%d", alias, usedAliases[alias])
		}
		routes[i].Alias = alias
	}
	return nil
}

func fillRoutePaths(routes []RouteSpec) {
	overrides := map[string]string{}
	for _, route := range routes {
		if route.PathOverride != "" {
			overrides[route.RelDir] = route.PathOverride
		}
	}
	for i := range routes {
		for j := range routes[i].Methods {
			path := routePath(routes[i].RelDir, overrides, routes[i].Methods[j].Param)
			routes[i].Methods[j].URLPath = path
			if routes[i].URLPath == "" {
				routes[i].URLPath = path
			}
		}
	}
}

func findModule(start string) (string, string, error) {
	dir := start
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				if strings.HasPrefix(line, "module ") {
					return dir, strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
				}
			}
			return "", "", fmt.Errorf("module directive not found in %s", filepath.Join(dir, "go.mod"))
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", fmt.Errorf("go.mod not found from %s", start)
		}
		dir = parent
	}
}

func routeAlias(rel string) string {
	parts := strings.FieldsFunc(rel, func(r rune) bool {
		return r == '/' || r == '-' || r == '_' || r == '[' || r == ']' || r == '.'
	})
	if len(parts) == 0 {
		return "route"
	}
	var b strings.Builder
	for i, part := range parts {
		if part == "" || part == "..." {
			continue
		}
		if i == 0 {
			b.WriteString(lowerName(part))
		} else {
			b.WriteString(exportName(part))
		}
	}
	if b.Len() == 0 {
		return "route"
	}
	return b.String()
}
