package generator

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedHeader = "// Code generated by frourio-go. DO NOT EDIT.\n\n"

func Generate(opts Options) error {
	if opts.APIDir == "" {
		return fmt.Errorf("api dir is required")
	}

	apiDir, err := filepath.Abs(opts.APIDir)
	if err != nil {
		return err
	}

	routes, err := scan(apiDir)
	if err != nil {
		return err
	}
	if len(routes) == 0 {
		return fmt.Errorf("no frourio.go files found under %s", apiDir)
	}
	fillRoutePaths(routes)
	if err := fillImportInfo(apiDir, routes); err != nil {
		return err
	}
	fillAncestors(routes)
	fillParamAncestors(routes)

	sort.Slice(routes, func(i, j int) bool {
		return routes[i].URLPath < routes[j].URLPath
	})

	if !opts.OnlyOpenAPI {
		for _, route := range routes {
			if err := writeGoFile(filepath.Join(route.Dir, "frourio_relay.go"), relayText(route)); err != nil {
				return err
			}
		}

		if err := writeGoFile(filepath.Join(apiDir, "frourio_server.go"), serverText(apiDir, routes)); err != nil {
			return err
		}
	}

	if opts.OpenAPIPath == "" {
		return nil
	}

	// Generated API documentation is source output, so it should be readable and traversable by the project owner.
	if err := os.MkdirAll(filepath.Dir(opts.OpenAPIPath), 0o755); err != nil { //nolint:gosec // Generated source directories should be traversable in the repository.
		return err
	}

	templatePath := opts.TemplatePath
	if templatePath == "" {
		templatePath = filepath.Join(filepath.Dir(opts.OpenAPIPath), "openapi_template.json")
	}
	template, err := loadOrCreateTemplate(templatePath, opts.TemplatePath != "")
	if err != nil {
		return err
	}

	doc := mergeOpenAPI(template, openAPIDocument(routes))
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(opts.OpenAPIPath, append(data, '\n'), 0o644) //nolint:gosec // Generated source artifact, not a secret.
}

// loadOrCreateTemplate reads the OpenAPI template at path. If the file doesn't
// exist and explicit is false (default-derived path), it writes a minimal
// skeleton there and returns it. If explicit is true, a missing file is an
// error — the user pointed us somewhere that should already exist.
func loadOrCreateTemplate(path string, explicit bool) (map[string]any, error) {
	data, err := os.ReadFile(path) //nolint:gosec // Template path is a user-controlled build-time input.
	if err == nil {
		var t map[string]any
		if err := json.Unmarshal(data, &t); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		return t, nil
	}
	if !os.IsNotExist(err) {
		return nil, err
	}
	if explicit {
		return nil, fmt.Errorf("template not found: %s", path)
	}

	skeleton := map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":   "frourio-go API",
			"version": "0.1.0",
		},
	}
	out, err := json.MarshalIndent(skeleton, "", "  ")
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil { //nolint:gosec // Generated source artifact.
		return nil, err
	}
	return skeleton, nil
}

// mergeOpenAPI overlays generated paths/components onto the template. The
// template provides info / servers / tags / security / etc.; generated keys
// (paths, components.schemas) always win over anything the template tried to
// declare under those slots.
func mergeOpenAPI(template, generated map[string]any) map[string]any {
	out := map[string]any{}
	for k, v := range template {
		out[k] = v
	}
	for k, v := range generated {
		if k == "components" {
			out[k] = mergeComponents(template["components"], v)
			continue
		}
		out[k] = v
	}
	return out
}

func mergeComponents(templateComponents, generated any) any {
	tc, _ := templateComponents.(map[string]any)
	gc, _ := generated.(map[string]any)
	if tc == nil {
		return gc
	}
	merged := map[string]any{}
	for k, v := range tc {
		merged[k] = v
	}
	for k, v := range gc {
		if k == "schemas" {
			merged[k] = mergeMaps(tc["schemas"], v)
			continue
		}
		merged[k] = v
	}
	return merged
}

func mergeMaps(template, generated any) any {
	tm, _ := template.(map[string]any)
	gm, _ := generated.(map[string]any)
	if tm == nil {
		return gm
	}
	merged := map[string]any{}
	for k, v := range tm {
		merged[k] = v
	}
	for k, v := range gm {
		merged[k] = v
	}
	return merged
}

func fillAncestors(routes []RouteSpec) {
	for i := range routes {
		for _, candidate := range routes {
			if candidate.RelDir == routes[i].RelDir || !hasMiddleware(candidate) {
				continue
			}
			if isAncestorRel(candidate.RelDir, routes[i].RelDir) {
				routes[i].Ancestors = append(routes[i].Ancestors, candidate)
			}
		}
		sort.Slice(routes[i].Ancestors, func(a, b int) bool {
			return len(routes[i].Ancestors[a].RelDir) < len(routes[i].Ancestors[b].RelDir)
		})
	}
}

func fillParamAncestors(routes []RouteSpec) {
	byRel := map[string]*RouteSpec{}
	for i := range routes {
		byRel[routes[i].RelDir] = &routes[i]
	}
	for i := range routes {
		rel := routes[i].RelDir
		if rel == "" {
			continue
		}
		parts := strings.Split(rel, "/")
		var ancestors []ParamAncestor
		for j := 1; j <= len(parts); j++ {
			ancestorRel := strings.Join(parts[:j], "/")
			ancestor, ok := byRel[ancestorRel]
			if !ok {
				continue
			}
			var paramField *FieldSpec
			for _, m := range ancestor.Methods {
				if m.Param != nil {
					p := *m.Param
					paramField = &p
					break
				}
			}
			if paramField == nil {
				continue
			}
			slug := parts[j-1]
			ancestors = append(ancestors, ParamAncestor{
				RelDir:   ancestorRel,
				SlugName: slug,
				FieldKey: exportName(sanitizeSlug(slug)),
				Param:    paramField,
			})
		}
		routes[i].ParamAncestors = ancestors
	}
}

func sanitizeSlug(slug string) string {
	parts := strings.FieldsFunc(slug, func(r rune) bool {
		return r == '-' || r == '_' || r == '.'
	})
	if len(parts) == 0 {
		return slug
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(lowerName(p))
		} else {
			b.WriteString(exportName(p))
		}
	}
	return b.String()
}

func isAncestorRel(parent, child string) bool {
	if parent == "" {
		return child != ""
	}
	return strings.HasPrefix(child, parent+"/")
}

func writeGoFile(path string, text string) error {
	formatted, err := format.Source([]byte(generatedHeader + text))
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	return os.WriteFile(path, formatted, 0o644) //nolint:gosec // Generated Go source should be readable in the repository.
}

func exportName(name string) string {
	if name == "" {
		return name
	}
	if strings.EqualFold(name, "body") {
		return "Body"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func lowerName(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func fillImportInfo(apiDir string, routes []RouteSpec) error {
	moduleRoot, modulePath, err := findModule(apiDir)
	if err != nil {
		return err
	}
	apiRel, err := filepath.Rel(moduleRoot, apiDir)
	if err != nil {
		return err
	}
	apiImport := modulePath + "/" + filepath.ToSlash(apiRel)

	usedAliases := map[string]int{}
	for i := range routes {
		rel := routes[i].RelDir
		if routes[i].RelDir == "" {
			routes[i].ImportPath = apiImport
			routes[i].Alias = ""
			continue
		}
		routes[i].ImportPath = apiImport + "/" + rel
		alias := routeAlias(rel)
		usedAliases[alias]++
		if usedAliases[alias] > 1 {
			alias = fmt.Sprintf("%s%d", alias, usedAliases[alias])
		}
		routes[i].Alias = alias
	}
	return nil
}

func fillRoutePaths(routes []RouteSpec) {
	overrides := map[string]string{}
	paramRels := map[string]*FieldSpec{}
	for _, route := range routes {
		if route.PathOverride != "" {
			overrides[route.RelDir] = route.PathOverride
		}
		for _, m := range route.Methods {
			if m.Param != nil {
				p := *m.Param
				paramRels[route.RelDir] = &p
				break
			}
		}
	}
	for i := range routes {
		for j := range routes[i].Methods {
			path := routePathWithAncestors(routes[i].RelDir, overrides, paramRels, routes[i].Methods[j].Param)
			routes[i].Methods[j].URLPath = path
			if routes[i].URLPath == "" {
				routes[i].URLPath = path
			}
		}
	}
}

func routePathWithAncestors(rel string, overrides map[string]string, paramRels map[string]*FieldSpec, ownParam *FieldSpec) string {
	if rel == "" {
		return "/"
	}
	var parts []string
	relParts := strings.Split(rel, "/")
	for i, part := range relParts {
		if part == "" {
			continue
		}
		currentRel := strings.Join(relParts[:i+1], "/")
		isLast := i == len(relParts)-1
		var p *FieldSpec
		if isLast {
			p = ownParam
		} else {
			p = paramRels[currentRel]
		}
		if p != nil {
			if p.Slice {
				parts = append(parts, "{"+part+"...}")
			} else {
				parts = append(parts, "{"+part+"}")
			}
			continue
		}
		if override := overrides[currentRel]; override != "" {
			parts = append(parts, override)
			continue
		}
		parts = append(parts, part)
	}
	return "/" + strings.Join(parts, "/")
}

func findModule(start string) (string, string, error) {
	dir := start
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod")) //nolint:gosec // The path is constrained to ancestor go.mod discovery.
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				if strings.HasPrefix(line, "module ") {
					return dir, strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
				}
			}
			return "", "", fmt.Errorf("module directive not found in %s", filepath.Join(dir, "go.mod"))
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", fmt.Errorf("go.mod not found from %s", start)
		}
		dir = parent
	}
}

func routeAlias(rel string) string {
	parts := strings.FieldsFunc(rel, func(r rune) bool {
		return r == '/' || r == '-' || r == '_' || r == '[' || r == ']' || r == '.'
	})
	if len(parts) == 0 {
		return "route"
	}
	var b strings.Builder
	for i, part := range parts {
		if part == "" || part == "..." {
			continue
		}
		if i == 0 {
			b.WriteString(lowerName(part))
		} else {
			b.WriteString(exportName(part))
		}
	}
	if b.Len() == 0 {
		return "route"
	}
	return b.String()
}
