// Code generated by frourio-go. DO NOT EDIT.

package raw

import (
	"context"
	"net/http"
)

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
}

type RawResponse interface {
	WriteHTTP(http.ResponseWriter, *http.Request) error
}

type RawResponseFunc func(http.ResponseWriter, *http.Request) error

func (f RawResponseFunc) WriteHTTP(w http.ResponseWriter, r *http.Request) error { return f(w, r) }

type GetResponse = RawResponse

type RouteHandlers struct {
	Get func(context.Context, GetRequest) (GetResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
