// Code generated by frourio-go. DO NOT EDIT.

package admin

import (
	"context"
	"net/http"
)

type RouteDefinition struct {
	spec     routeMetadata
	handlers RouteHandlers
}

type routeMetadata struct{}

var routeSpec = routeMetadata{}

type GetRequest struct {
}

type GetResponse interface {
	isGetResponse()
	StatusCode() int
}

type GetStatus200 struct {
	Body AdminContextResponse
}

func (GetStatus200) isGetResponse()  {}
func (GetStatus200) StatusCode() int { return 200 }

type PostRequest struct {
	Body AdminPostBody
}

type PostResponse interface {
	isPostResponse()
	StatusCode() int
}

type PostStatus201 struct {
	Body AdminPostResponseBody
}

func (PostStatus201) isPostResponse() {}
func (PostStatus201) StatusCode() int { return 201 }

type PostStatus403 struct {
	Body ForbiddenBody
}

func (PostStatus403) isPostResponse() {}
func (PostStatus403) StatusCode() int { return 403 }

type MiddlewareAllContext struct {
	IsAdmin     bool     `json:"isAdmin"`
	Permissions []string `json:"permissions"`
}

type MiddlewareContext struct {
	UserID  *string `json:"userId"`
	TraceID string  `json:"traceId" validate:"required"`
	MiddlewareAllContext
}

type MiddlewareNext func(context.Context, MiddlewareAllContext) (any, error)
type MiddlewareAll func(context.Context, *http.Request, MiddlewareNext) (any, error)

type GetContext struct {
	MiddlewareContext
}

type PostContext struct {
	MiddlewareContext
}

type PostNext func(context.Context, PostRequest) (PostResponse, error)
type PostMiddleware func(context.Context, *http.Request, PostRequest, MiddlewareContext, PostNext) (PostResponse, error)

type RouteMiddleware struct {
	All  MiddlewareAll
	Post PostMiddleware
}

type RouteHandlers struct {
	Middleware RouteMiddleware
	Get        func(context.Context, GetRequest, GetContext) (GetResponse, error)
	Post       func(context.Context, PostRequest, PostContext) (PostResponse, error)
}

func DefineRoute(handlers RouteHandlers) RouteDefinition {
	return RouteDefinition{spec: routeSpec, handlers: handlers}
}

func (route RouteDefinition) Handlers() RouteHandlers {
	return route.handlers
}
